### ISSUE TITLE
lxml.etree Import Error on M1 mac

### ISSUE THREAD

**Issue by AndyTheFactory** [AndyTheFactory/newspaper4k#547]
<a href="https://github.com/martin2903"><img src="https://avatars.githubusercontent.com/u/71020261?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [martin2903](https://github.com/martin2903)**
_Mon Jan  3 13:53:05 2022_
_Originally opened as https://github.com/codelucas/newspaper/issues/929_

----

Trying to use newspaper3k on m1 mac gives the following error:
ImportError: dlopen(/Users/---/PycharmProjects/testProject/venv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'

I followed all instructions listed, including installing lxml using brew - to no avail.

Any suggestions?

**Comment by AndyTheFactory** [comment]
https://stackoverflow.com/questions/70862598/scrapy-startproject-command-failed-on-import-etree-mac-m1-the-error-message-is

`pip3 uninstall lxml
`
then

`pip3 install lxml --no-cache-dir `
it will force redownload and build wheel

**Comment by smyja** [comment]
or downgrade to 4.9.4
