### ISSUE TITLE
Is the summary feature working? 

### ISSUE THREAD

**Issue by AndyTheFactory** [AndyTheFactory/newspaper4k#59]
<a href="https://github.com/dustyny"><img src="https://avatars.githubusercontent.com/u/7416333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dustyny](https://github.com/dustyny)**
_Sat Nov 26 20:01:24 2016_
_Originally opened as https://github.com/codelucas/newspaper/issues/306_

----

I've run 3 publications (100k articles) through newspaper and summary is coming up empty on all articles. I've  made sure I'm parsing & running nlp before running it but no luck. 

Anyone else having luck with this feature? 
Am I missing something?

**Comment by mightym** [comment]
@AndyTheFactory I'm encountering the same issue. I have around 500 newspaper articles. The text and title gets parsed but none of the articles have summaries.

**Comment by AndyTheFactory** [comment]
you must run `article.nlp()` to get a summary
