### ISSUE TITLE
Playwright example

### ISSUE THREAD

**Issue by palfrey** [AndyTheFactory/newspaper4k#595]
https://github.com/AndyTheFactory/newspaper4k/blob/master/docs/user_guide/examples.rst lists "Using Playwright to Scrape Websites built with Javascript", and I've just done this, but don't have the time to write the full doc PR

This isn't the full code, as it's taken from a closed-source project of mine (but feel free to use this bit), but gets the idea across

```python
from playwright.sync_api import sync_playwright
from newspaper import Article

article = Article(url)
article.download()
article.parse()
if article.text == "":
    with sync_playwright() as p:
        browser = p.firefox.launch()
        page = browser.new_page()
        page.goto(url)
        article.set_html(page.content())
        article.parse()
```

This let me parse https://garnix.io/blog/garn-v0_0_18 which was entirely JS generated

**Comment by AndyTheFactory** [comment]
Hi @palfrey !

Thanks, 
It's a huge help to have such examples!

I will definitely use this for the next update of the docs (right after the 0.9.2 release)

Andrei

**Comment by AndyTheFactory** [comment]
added https://newspaper4k.readthedocs.io/en/documentation-changes-v0.9.2/user_guide/examples.html#using-playwright-to-scrape-websites-built-with-javascript
