### ISSUE TITLE
Python <3.8 support?

### ISSUE THREAD

**Issue by palfrey** [AndyTheFactory/newspaper4k#612]
I'm poking at things trying to add typing support and hitting the issue that some of the supporting packages don't have a Python 3.6 version with types. e.g. tldextract only has types from 3.2.0, and that has a minimum Python support of 3.7

Given also that https://devguide.python.org/versions/ notes 3.6 and 3.7 are both EoL, is it worth still supporting them here? I'll note they're not checked in the CI. Relatedly, its probably worth adding 3.10/11/12 to the CI builds.

**Comment by AndyTheFactory** [comment]
Hi,
you are right, there is no much sense to keep the <3.8 support. 
I wanted to keep it for the first couple of releases to make the transition easier for users of newspaper3k (which supported 3.6 )

I think for the next release it makes sense to drop the old version support, as you suggest

**Comment by palfrey** [comment]
https://github.com/AndyTheFactory/newspaper4k/pull/614 implements this, and adds 3.10/11/12 testing.

**Comment by palfrey** [comment]
614 isn't properly tested yet, as PRs don't get run through the Github actions flow. https://github.com/AndyTheFactory/newspaper4k/pull/615 fixes this.

**Comment by AndyTheFactory** [comment]
Merged
