### ISSUE TITLE
[BUG] bbc.com news languages don't work

### ISSUE THREAD

**Issue by smyja** [AndyTheFactory/newspaper4k#620]
**Describe the bug**
I am trying to get the text and possibly all the bbc links for the language and it keeps printing blank and showing 0 urls. Nothing for bbc yoruba works.

**To Reproduce**
Steps to reproduce the behavior, please post any code you used and the website you tried to parse/process:
```
from newspaper import Article

article = Article('https://www.bbc.com/yoruba/articles/c04lkx8ll52o')

print(article.text)
```
**Expected behavior**

**Screenshots**

**System information**
 - OS: [Windows / Linux / Macos]
 - Python version [e.g. 3.6, 3.9]
 - Library version [e.g. 0.9.0]

**Additional context**

**Comment by AndyTheFactory** [comment]
Hello Smyja,

The proper way to call the library is 

```
article = Article('https://www.bbc.com/yoruba/articles/c04lkx8ll52o', language='yo')
article.download()
article.parse()

```

unfortunately, Yoruba Language is not (yet) supported. There is no stopwords list in our library in order to analyse the Yoruba Language articles.
Do you know a good resource for this? Also, since i'm not familiar with your language, is there a special tokenization rule for Yoruba? or does tokenization work with spaces and common punctuation ?

**Comment by smyja** [comment]
> Hello Smyja,
> 
> The proper way to call the library is
> 
> ```
> article = Article('https://www.bbc.com/yoruba/articles/c04lkx8ll52o', language='yo')
> article.download()
> article.parse()
> ```
> 
> unfortunately, Yoruba Language is not (yet) supported. There is no stopwords list in our library in order to analyse the Yoruba Language articles. Do you know a good resource for this? Also, since i'm not familiar with your language, is there a special tokenization rule for Yoruba? or does tokenization work with spaces and common punctuation ?

Here are the stopwords list. Maskhane own is more recent.
https://github.com/masakhane-io/masakhanePreprocessor/blob/main/african-stopwords/languages/yo.txt
https://github.com/stopwords-iso/stopwords-yo/blob/master/stopwords-yo.json

**Comment by AndyTheFactory** [comment]
Ok, i have added them for the next release.
