### ISSUE TITLE
[BUG] Title length is limited to 200 characters additional characters are sliced

### ISSUE THREAD

**Issue by pankajjha** [AndyTheFactory/newspaper4k#631]
**Describe the bug**
Any article which has more than 200 characters title is sliced to only 200 characters. Additional characters are removed.
This is across all the websites and not specific to any website.

**To Reproduce**
Here are some urls whose title is more than 200 characters and is sliced in the extracted results.
1. https://pankajjha.me/test2.html
2. https://www.dailymail.co.uk/news/article-12621977/King-Charles-William-Kate-BBC-Hamas-Israel.html
3. https://www.dailymail.co.uk/femail/article-12622453/Jada-Pinkett-Smith-body-language-separation.html

**Expected behavior**
Extraction should extract the complete title without any modification or slicing in the title.

**Comment by AndyTheFactory** [comment]
Hello,

you can use the "max_title" configuration setting. For  instance:

```python
    url = "https://www.dailymail.co.uk/news/article-12621977/King-Charles-William-Kate-BBC-Hamas-Israel.html"
    a = newspaper.article(url, max_title=1000)
    print(a.title)
```
