### ISSUE TITLE
[SITES] cs.brown.edu

### ISSUE THREAD

**Issue by palfrey** [AndyTheFactory/newspaper4k#634]
### First please check that it is really an issue with the library, and not some special case of website:

- [x] There is no paywall
- [x] You do not have to be logged in to see the articles
- [x] You tried using a common browser user agent in your configuration / call
- [x] The website is not in the list of well known problematic sites

# Your report as follows:

**Website that does not parse correctly:**

> cs.brown.edu

**Some sample urls that I have tried**

> https://cs.brown.edu/~sk/Publications/Papers/Published/lk-smol-tutor/

**The exact code i used to test this articles/website**

```python
article = Article("https://cs.brown.edu/~sk/Publications/Papers/Published/lk-smol-tutor/, fetch_images=False, follow_meta_refresh=True)
article.download()
article.parse()
```

** What parts of the article are missing / not parsed correctly **

All

**Other information, remarks, messages, etc:**

The problem is because apparently the HTTPS cert is bad. I can probably fix this with some requests magic

Article `download()` failed with HTTPSConnectionPool(host='cs.brown.edu', port=443): Max retries exceeded with url: /~sk/Publications/Papers/Published/lk-smol-tutor/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) on URL

**Comment by AndyTheFactory** [comment]
you can use just:
```
article = newspaper.article('https://cs.brown.edu/~sk/Publications/Papers/Published/lk-smol-tutor/', verify=False,)
```
