### ISSUE TITLE
[BUG] Responses with no headers break some of the internal code

### ISSUE THREAD

**Issue by palfrey** [AndyTheFactory/newspaper4k#635]
**Describe the bug**

https://www.solidot.org/story?sid=77884 returns a 401 with no headers, which breaks stuff

```python
url = 'https://www.solidot.org/story?sid=77884', config = <newspaper.configuration.Configuration object at 0x7fae1612ea50>

    def do_request(url: str, config: Configuration) -> Response:
        """Perform a HTTP GET request to the specified URL using the provided configuration.
        Args:
            url (str): The URL to send the request to.
            config (Configuration): The configuration object containing request parameters.

        Returns:
            requests.Response: The response object containing the server's response
                to the request.
        """
>       session.headers.update(config.requests_params["headers"])
E       KeyError: 'headers'

../../../../.pyenv/versions/3.11.5/envs/freshet/lib/python3.11/site-packages/newspaper/network.py:208: KeyError
```

**To Reproduce**
Steps to reproduce the behavior, please post any code you used and the website you tried to parse/process:
```python
article = Article(
        "https://www.solidot.org/story?sid=77884",
        fetch_images=False,
        follow_meta_refresh=True,
        requests_params={"verify": False},
    )
article.download()
```

**Expected behavior**

Parse failure, but not a `KeyError`

**System information**
 - OS: Linux
 - Python version: 3.11
 - Library version: 0.9.3.1 (also repo'ed on 0.9.2)

**Comment by palfrey** [comment]
Huh. The problem was the `request_params` which was a workaround for https://github.com/AndyTheFactory/newspaper4k/issues/634. Adding `"headers": {}` to that as well fixed things, but that was not expected.

**Comment by AndyTheFactory** [comment]
yeah, i noticed that too. will fix it

**Comment by AndyTheFactory** [comment]
Fixed in https://github.com/AndyTheFactory/newspaper4k/commit/802ae11d9cf543cf771822271604ed167d366646
